---
apiVersion: v1
kind: Namespace
metadata:
  name: clusters
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-provisioner
  namespace: clusters

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-provisioner
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["hypershift.openshift.io"]
  resources: ["hostedclusters"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["hypershift.openshift.io"]
  resources: ["nodepools"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-provisioner-rb
  namespace: clusters
subjects:
- kind: ServiceAccount
  name: cluster-provisioner
  namespace: clusters
roleRef:
  kind: ClusterRole
  name: cluster-provisioner
  apiGroup: rbac.authorization.k8s.io
