---
apiVersion: v1
kind: Namespace
metadata:
  name: clusters
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-space
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-provisioner
  namespace: clusters

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-provisioner
  namespace: tenant-space

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-provisioner
rules:
# The hypershift CLI applies some labels on the namespace
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - patch
# The user and hypershift CLI require CRUD for secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# Grant full control of hypershift resources
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedclusters
  - nodepools
  verbs:
  - "*"
# Grant full control of ClusterTemplateInstances
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplateinstances
  verbs:
  - "*"
# Allow looking up available ClusterTemplates
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplates
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-provisioner-rb
  namespace: clusters
subjects:
- kind: ServiceAccount
  name: cluster-provisioner
  namespace: clusters
roleRef:
  kind: ClusterRole
  name: cluster-provisioner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-provisioner-rb
  namespace: tenant-space
subjects:
- kind: ServiceAccount
  name: cluster-provisioner
  namespace: tenant-space
roleRef:
  kind: ClusterRole
  name: cluster-provisioner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oidc-configmap-reader
  namespace: kube-public
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - oidc-storage-provider-s3-config
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-configmap-reader-rb
  namespace: kube-public
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: oidc-configmap-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: supported-versions-reader
  namespace: hypershift
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - supported-versions
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: supported-versions-reader-rb
  namespace: hypershift
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: supported-versions-reader
  apiGroup: rbac.authorization.k8s.io
