---
apiVersion: clustertemplate.openshift.io/v1alpha1
kind: Config
metadata:
  name: config
spec:
  argoCDNamespace: openshift-gitops
  uiEnabled: false

---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
 name: openshift-gitops
 namespace: openshift-gitops
spec:
 resourceTrackingMethod: annotation

---
apiVersion: clustertemplate.openshift.io/v1alpha1
kind: ClusterTemplate
metadata:
  name: hypershift-aws-template
spec:
  clusterDefinition: hypershift-aws-template-appset
  skipClusterRegistration: true
  cost: 1

---
apiVersion: clustertemplate.openshift.io/v1alpha1
kind: ClusterTemplate
metadata:
  name: hypershift-aws-self-service-template
spec:
  clusterDefinition: hypershift-aws-self-service-template-appset
  skipClusterRegistration: true
  cost: 1

---
apiVersion: clustertemplate.openshift.io/v1alpha1
kind: ClusterTemplateQuota
metadata:
  name: quota
  namespace: clusters
spec:
  budget: 100
  allowedTemplates:
    - name: hypershift-aws-template
      deleteAfter: 2h

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hypershift-aws-template-appset
  namespace: openshift-gitops
spec:
  generators:
    - {}
  template:
    metadata:
      # Workaround for https://github.com/argoproj/argo-cd/issues/17181
      finalizers:
        - resources-finalizer.argocd.argoproj.io
        - post-delete-finalizer.argocd.argoproj.io
        - post-delete-finalizer.argocd.argoproj.io/cleanup
    spec:
      destination:
        namespace: clusters
        server: '{{ url }}'
      project: default
      source:
        chart: hypershift-aws-template
        repoURL: https://konflux-ci.dev/cluster-template-charts/
        targetRevision: 0.0.2
        helm:
          parameters:
            - name: baseDomain
              value: eaasdemo.com
            - name: region
              value: us-east-1
            - name: secret
              value: hypershift
            - name: serviceAccount
              value: cluster-provisioner
            - name: hypershiftImageTag
              value: latest
            - name: nodePoolReplicas
              value: "3"
      syncPolicy:
        automated: {}

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hypershift-aws-self-service-template-appset
  namespace: openshift-gitops
spec:
  generators:
    - {}
  template:
    metadata:
      # Workaround for https://github.com/argoproj/argo-cd/issues/17181
      finalizers:
        - resources-finalizer.argocd.argoproj.io
        - post-delete-finalizer.argocd.argoproj.io
        - post-delete-finalizer.argocd.argoproj.io/cleanup
    spec:
      destination:
        namespace: '{{ instance_ns }}'
        server: '{{ url }}'
      project: default
      source:
        chart: hypershift-aws-template
        repoURL: https://konflux-ci.dev/cluster-template-charts/
        targetRevision: 0.0.2
        helm:
          parameters:
            - name: serviceAccount
              value: cluster-provisioner
            - name: hypershiftImageTag
              value: latest
      syncPolicy:
        automated: {}
